### ISSUE TITLE
getDefaultTracker() method not available

### ISSUE THREAD

**Issue by rjhashlearn** [segment-integrations/analytics-android-integration-google-analytics#2]
I'm using this dependency - 

```
compile('com.segment.analytics.android:analytics-integration-google-analytics:+') {
        transitive = true
    }
```

I need a reference to tracker for performing custom actions. According to this [doc](https://segment.com/docs/integrations/google-analytics/#mobile-apps), getDefaultTracker() gives this. But unable to call getDefaultTracker() on GoogleAnalytics object.

**Comment by f2prateek** [comment]
Why not?

**Comment by rjhashlearn** [comment]
@f2prateek No idea. These are the only set of methods available - 

```
 mGoogleAnalytics.getAppOptOut();
 mGoogleAnalytics.getClientId();
mGoogleAnalytics.getAppOptOut();
```

Also, I've changed the dependency to this and tried - 

 compile('com.segment.analytics.android.integrations:google-analytics:1.1.0') {
        transitive = true
    }

**Comment by brennan** [comment]
Hey @rjhashlearn, if you're still curious, we provide examples of how to access underlying instances here: https://segment.com/docs/sources/mobile/android/#how-can-i-use-an-destination-specific-feature-e-g-mixpanel-s-push-notifications-. Google Analytics would return the `Tracker` object, seen here:  https://github.com/segment-integrations/analytics-android-integration-google-analytics/blob/master/src/main/java/com/segment/analytics/android/integrations/google/analytics/GoogleAnalyticsIntegration.java#L378-L380
